---
title: "FIT_mes"
author: "J_Munera"
date: "6/23/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##MODELO DE PREDICCION PARA MESES:


## GENERACION DE TUPLAS PARA BARRIOS
```{r}
date_filler_bar <- function(barrio, inicio, fin){
  #inicio y fin: vectores con "año" en la posición uno y mes en las dos
  
  inicio <- as.Date(paste(inicio[1], inicio[2], 1, sep="-"), "%Y-%m-%d")
  fin <- as.Date(paste(fin[1], fin[2], 1, sep="-"), "%Y-%m-%d")
  
  dates <- data.frame(FECHA=seq(inicio, fin,by = "month"))
  #return(dates)
  dates <- dates%>% mutate(
    BARRIO = barrio,
    PERIODO = as.numeric(format(FECHA ,"%Y")),
    MES = as.numeric(as.factor(format(FECHA ,"%m")))
    
  )
  return(dates[,-1]) 
}


```

## GENERACION DE TUPLAS PARA COMUNAS
```{r}
date_filler_com <- function(comuna, inicio, fin){
  
  inicio <- as.Date(paste(inicio[1], inicio[2], 1, sep="-"), "%Y-%m-%d")
  fin <- as.Date(paste(fin[1], fin[2], 1, sep="-"), "%Y-%m-%d")
  
  dates <- data.frame(FECHA=seq(inicio, fin,by = "month"))
  #return(dates)
  dates <- dates%>% mutate(
    COMUNA = comuna,
    PERIODO = as.numeric(format(FECHA ,"%Y")),
    MES = as.numeric(as.factor(format(FECHA ,"%m")))
    
  )
  return(dates[,-1]) 
}


```


##CARGA BASES DE DATOS DEL ENTRENAMIENTO Y LOS MODELOS
```{r}
df.barrio <- read.csv("barrios_mes.csv", stringsAsFactors = FALSE, encoding = "ISO_8859-1", header = T)

df.comuna <- read.csv("comunas_mes.csv", stringsAsFactors = FALSE, encoding = "ISO_8859-1", header = T)


load("./Modelos_finales/com.mes.1_2.RData") ## carga los modelos de comunas
load("./Modelos_finales/bar.mes.1_2.RData")
```


```{r}
#load("./Modelos_finales/com.dia.1_2.RData") ## carga los modelos

predicciones_meses <- function(com.or.bar, inicio, final, nombre){
  #com.or.bar: T = com; F = bar
  #inicio: fecha de inicio
  #final: fecha de finalizacion
  #nombre: nombre de la comuna o del barrio
  if(com.or.bar){
    datos <- date_filler_com(nombre, inicio, final) #datos a predecir
    modelo1 <- filter(com.mes.1, Comuna== nombre)$Reg.obj[[1]]
    modelo2 <- filter(com.mes.2, Comuna== nombre)$Reg.obj[[1]]
    tr1 <- filter(df.comuna, COMUNA==nombre, PERIODO !=2018)#datos de entrenamietno del modelo
    tr2 <- filter(df.comuna, COMUNA==nombre, PERIODO !=2018 & PERIODO !=2017)
    
  }else{
    #TODO VERIFICAR
    datos <- date_filler_bar(nombre, inicio, final)
    
    modelo1 <- filter(bar.mes.1, Barrio== nombre)$Reg.obj[[1]]
    modelo2 <- filter(bar.mes.2, Barrio== nombre)$Reg.obj[[1]]
    
    tr1 <- filter(df.barrio, BARRIO==nombre, PERIODO !=2018)#datos de entrenamietno del modelo
    tr2 <- filter(df.barrio, BARRIO==nombre, PERIODO !=2018 & PERIODO !=2017)
  }
  y1 <- predict(modelo1, newdata = datos, data= tr1)
  y2 <- predict(modelo2, newdata = datos, data= tr2)
  
  return(c(sum(y1), sum(y2)))
  
  
}

##EJEMPLO:
##para barrio
prediccion <- predicciones_meses(F, c(2019, 5), c(2019,10), "Aldea Pablo VI")

```
