---
title: "Fitting"
author: "J_Munera"
date: "6/23/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##MODELO DE PREDICCION PARA SEMANAS:


## GENERACION DE TUPLAS PARA BARRIOS
```{r}
date_filler_bar <- function(barrio, inicio, fin){
  #inicio y fin: vectores con "año" en la posición uno y semana en las dos
  
  inicio <- as.Date(paste(inicio[1], inicio[2], 1, sep="-"), "%Y-%U-%u")
  fin <- as.Date(paste(fin[1], fin[2], 1, sep="-"), "%Y-%U-%u")
  
  dates <- data.frame(FECHA=seq(inicio, fin,by = "week"))
  #return(dates)
  dates <- dates%>% mutate(
    BARRIO = barrio,
    PERIODO = as.numeric(format(FECHA ,"%Y")),
    MES = as.numeric(as.factor(format(FECHA ,"%m"))),
    SEMANA = as.factor(as.numeric(format(FECHA ,"%U"))),
    Fecha = FECHA
    
  )
  return(dates[,-1]) 
}
s <- date_filler_bar("La candelaria", c(2019, 1), c(2019,52))

```

## GENERACION DE TUPLAS PARA COMUNAS
```{r}
date_filler_com <- function(comuna, inicio, fin){
  
  inicio <- as.Date(paste(inicio[1], inicio[2], 1, sep="-"), "%Y-%U-%u")
  fin <- as.Date(paste(fin[1], fin[2], 1, sep="-"), "%Y-%U-%u")
  
  dates <- data.frame(FECHA=seq(inicio, fin,by = "week"))
  
  dates <- dates%>% mutate(
    COMUNA = comuna,
    PERIODO = as.numeric(format(FECHA ,"%Y")),
    MES = as.numeric(as.factor(format(FECHA ,"%m"))),
    SEMANA = as.factor(as.numeric(format(FECHA ,"%U"))),
    Fecha = FECHA
    
  )
  return(dates[,-1])
   
}


```


##CARGA BASES DE DATOS DEL ENTRENAMIENTO Y LOS MODELOS
```{r}
#df.barrio <- read.csv("barrios_sem.csv", stringsAsFactors = FALSE, encoding = "ISO_8859-1", header = T)

df.comuna <- read.csv("comunas_sem.csv", stringsAsFactors = FALSE, encoding = "ISO_8859-1", header = T)

load("./Modelos_finales/com.sem.1_2.RData") ## carga los modelos de comunas
load("./Modelos_finales/bar.sem.1_2.RData") 

```


```{r}
#load("./Modelos_finales/com.dia.1_2.RData") ## carga los modelos

predicciones_semana <- function(com.or.bar, inicio, final, nombre){
  #com.or.bar: T = com; F = bar
  #inicio: fecha de inicio
  #final: fecha de finalizacion
  #nombre: nombre de la comuna o del barrio
  if(com.or.bar){
    datos <- date_filler_com(nombre, inicio, final) #datos a predecir
    
    modelo1 <- filter(com.sem.1, Comuna== nombre)$Reg.obj[[1]]
    #modelo2 <- filter(com.sem.2, Comuna== nombre)$Reg.obj[[1]]
    
    tr1 <- filter(df.comuna, COMUNA==nombre, PERIODO !=2018)#datos de entrenamietno del modelo
    #tr2 <- filter(df.comuna, COMUNA==nombre, PERIODO !=2018 & PERIODO !=2017)
    #return(tr1)
    y1 <- predict(modelo1, newdata = datos[,-5], data= tr1)
    #y2 <- predict(modelo2, newdata = datos, data= tr2)
  }else{
    #TODO VERIFICAR
    datos <- date_filler_bar(nombre, inicio, final)
    modelo1 <- filter(bar.sem.1, Barrio== nombre)$Reg.obj[[1]]
    #modelo2 <- filter(bar.sem.2, Barrio== nombre)$Reg.obj[[1]]
    #tr1 <- filter(df.barrio, BARRIO==nombre, PERIODO !=2018)#datos de entrenamietno del modelo
    #tr2 <- filter(df.comuna, BARRIO==nombre, PERIODO !=2018 & PERIODO !=2017)
    
    y1 <- predict(modelo1, newdata = datos[,-5])
    #y2 <- predict(modelo2, newdata = datos)
  }
  
  
  total <- sum(y1)
  df <- cbind(datos, y1)
  
  p<-ggplot(data = df, aes(y= y1, x = as.Date(Fecha), col=as.factor(PERIODO)))+ geom_point()+
     geom_line()+
  theme(legend.position="top")+
  theme_bw()+
    scale_x_date(date_labels = "%U")+
  labs(title=paste("Accidentalidad en", nombre),
        x ="Semana", y = "Número de accidentes", col="Periodo")
  
  output <- list(df, round(total), p)
  names(output) <- c("Datos", "total accidentes", "grafico")
  return(output)
  
}

##EJEMPLO:
#prediccion <- predicciones_semana(T, c(2018, 50), c(2019,52), "La Candelaria")

prediccion <- predicciones_semana(F, c(2019, 1), c(2020,52), "Aures No.1")
print(prediccion$grafico)
```