---
title: "Modelo regresion dias"
author: "J_Munera"
date: "6/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(gamlss)
library(MASS)
```

## Lectura base por días:

```{r}
df.barrio <- read.csv("barrios_dia_esp.csv", stringsAsFactors = FALSE, encoding = "ISO_8859-1", header = T)

df.comuna <- read.csv("comunas_dias_esp.csv", stringsAsFactors = FALSE, encoding = "ISO_8859-1", header = T)

dias.especiales <-  read.csv("dias_espe.csv", stringsAsFactors = FALSE, encoding = "ISO_8859-1", header = T)

df.barrio <- df.barrio[,c(-1,-10)] 
df.comuna<-df.comuna[,c(-1,-10)] 

```


## Aplicación del modelo:

## Modelo Barrios


## Función de modelo


```{r}
library(magrittr)
df.comuna %<>% mutate(DIA_NUM = as.factor(DIA_NUM))
df.comuna %<>% mutate(MES = as.factor(MES))
df.comuna %<>% mutate(especial = as.factor(especial))


df.barrio %<>% mutate(DIA_NUM = as.factor(DIA_NUM))
df.barrio %<>% mutate(MES = as.factor(MES))
df.barrio %<>% mutate(especial = as.factor(especial))
```

```{r}
dias.especiales <- dias.especiales%>%
  mutate(
    FECHA = as.Date(paste(PERIODO,MES,DIA,sep="-"))
  )
```

##Experiment with dates
```{r}
date_filler <- function(df, barrio){
  df$FECHA<-as.Date(df$FECHA)
  df <- df[,-6]
  dates <- data.frame(FECHA=seq(as.Date('2014-01-01'),as.Date('2018-01-31'),by = 1))
  data <- full_join(df,dates)
  
  data <- data%>% mutate(
    BARRIO = barrio,
    PERIODO = as.numeric(format(FECHA ,"%Y")),
    MES = as.factor(format(FECHA ,"%m")),
    DIA = as.numeric(format(FECHA ,"%d")),
    DIA_NUM = as.factor(ifelse(as.POSIXlt(FECHA)$wday==0, 7, as.POSIXlt(FECHA)$wday)),
    especial = ifelse(FECHA %in% dias.especiales$FECHA, 1, 0)
  )
  data[is.na(data)] <- 0
  return(data)  
}
#example:
#dates <- filter(df.barrio,BARRIO=="María Cano Carambolas")
#dates <- date_filler(dates, "María Cano Carambolas")

```

experiments
```{r}
library(gamlss)
tr_data <- filter(df.comuna, PERIODO!=2018)
va_data <- filter(df.comuna, PERIODO==2018)

test_df <- filter(df.comuna, COMUNA=="")
formulas = c(formula("total~DIA_NUM+DIA+I(PERIODO^2)+MES+PERIODO"),
            formula("total~DIA_NUM+DIA+MES+PERIODO"),
            formula("total~DIA_NUM+I(PERIODO^2)+MES+PERIODO"),
            formula("total~DIA_NUM+MES+DIA"),
            formula("total~DIA_NUM+MES")
)

mse_tr.v <- c()
mse_val.v <- c()
for(formula in formulas){
  model <- gamlss(formula = formula, data = tr_data)
  model2 <- gamlss(formula = formula, data = tr_data, family=PO(mu.link = "identity"))
  #mse_tr.v  <- c(mse_tr.v, mean((tr_data$total - predict(poisson.model, new=tr_data))^2))
  #m.mse_va <- mean((va_data$total - predict(model,data= va_data))^2)
  #mse_val.v <- c(mse_val.v, mean((va_data$total - predict(poisson.model,new= va_data))^2))
  
  mse_tr.v  <- c(mse_tr.v, mean((tr_data$total - predict(model, newdata=tr_data, data=tr_data))^2))
  #m.mse_va <- mean((va_data$total - predict(model,data= va_data))^2)
  mse_val.v <- c(mse_val.v, mean((va_data$total - predict(model,newdata= va_data, data=tr_data))^2))
  
  mse_tr.v  <- c(mse_tr.v, mean((tr_data$total - predict(model2, newdata=tr_data, data=tr_data))^2))
  #m.mse_va <- mean((va_data$total - predict(model,data= va_data))^2)
  mse_val.v <- c(mse_val.v, mean((va_data$total - predict(model2,newdata= va_data,data=tr_data))^2))
}

results <- data.frame(mse_tr = mse_tr.v , mse_va = mse_val.v)
#results$form <- formula
```


## Función de modelo
```{r}
adj_model_com <- function(formulas, tr_data, val_data, zero_ex_cond = F){
  
    ## determina si el modelo es para Comunas o Barrios
  if("COMUNA" %in% colnames(tr_data)){
    com <- unique(tr_data$COMUNA)
  }else{
    com <- unique(tr_data$BARRIO)
  }
  
  results <- data.frame(matrix(ncol=7, nrow=0))
  tr_data2 <- tr_data
  val_data2 <- val_data

  for(co in com){
    
    if(zero_ex_cond){
      temp <- rbind(tr_data2, val_data2)
      temp <- date_filler(filter(temp, BARRIO==co), co)
      tr_data <- filter(temp, PERIODO!=2018)
      val_data <- filter(temp, PERIODO==2018)
    }
    
    
    print(co)
    if("COMUNA" %in% colnames(tr_data)){
      
      temp_tr <- filter(tr_data, COMUNA==co)
      temp_va <- filter(val_data, COMUNA==co)
      ub_name <- "Comuna"
    }
    else{
      temp_tr <- filter(tr_data, BARRIO==co)
      temp_va <- filter(val_data, BARRIO==co)
      ub_name <- "Barrio"
    }
    
    results2 <- data.frame(matrix(ncol=7, nrow=0)) #matriz de resultados para cada formula
    
    
    for(formula in formulas){
      mse_tr.v  <- c()
      mse_val.v <- c()
      
      #model2 <- glm(formula = formula, data = temp_tr)
      model1 <- gamlss(formula = formula, data = temp_tr, family=NO(mu.link = "identity"))
      #model2 <- gamlss(formula = formula, data = temp_tr, family=PO(mu.link = "identity"))
      #model3 <- gamlss(formula = formula, data = temp_tr, family=NBI(mu.link = "identity")) SE COMENTA PARA BARRIOS
      
      #model2 <- zeroinfl(formula = formula, data = temp_tr)

      
      list_models = list(model1)#QUite model3
      
      
       
       mse_tr.v  <- c(mse_tr.v, mean((temp_tr$total - predict(model1, newdata=temp_tr,data=temp_tr))^2))
       
      mse_val.v <- c(mse_val.v, mean((temp_va$total - predict(model1,newdata= temp_va,data=temp_tr))^2))

      
      
      #mse_tr.v  <- c(mse_tr.v, mean((temp_tr$total - predict(model2, data=temp_tr))^2))
      #mse_val.v <- c(mse_val.v, mean((temp_va$total - predict(model2,data= temp_va))^2))
      
      
      
      #mse_tr.v  <- c(mse_tr.v, mean((temp_tr$total - predict(model3, newdata=temp_tr,data=temp_tr))^2))
      #mse_val.v <- c(mse_val.v, mean((temp_va$total - predict(model3,newdata= temp_va,data=temp_tr))^2))#SECOMENTA PARA BARRIOS
      
      
      temp <- data.frame(mse_tr = mse_tr.v , mse_va = mse_val.v)
      temp$modelo <- list_models
      
      best_model <- filter(temp, mse_va == min(temp$mse_va))
      
      best_model$com_bar <- co
      
      best_model$family <- best_model$model[[1]]$family[1]
      
      best_model$form <- format(formula(best_model$model[[1]], what = c("mu")))
      
      results2 <- rbind(results2, best_model)
    }
    results <- rbind(results,  filter(results2, mse_va == min(results2$mse_va)))
    
      
  }
  
  trans <- function(x) as.numeric(as.character(x))
  results[, 1:2] <- sapply(results[, 1:2], trans)
  #COnvierte los errores a variables numericas
  
  colnames(results) <- c("MSE.tr", "MSE.va","Reg.obj", ub_name, "Family", "Formula")
  results <- results[,c(4,1,2,5,6,3)]
  return(results)
  

}
  
```

##MODELO PARA COMUNA_DIAS TR=2014-2017
```{r}
TR_data <- filter(df.comuna, PERIODO!=2018)
VA_data <- filter(df.comuna, PERIODO==2018)

formulas = c(formula("total~DIA_NUM+DIA+I(PERIODO^2)+MES+PERIODO"),
            formula("total~DIA_NUM+DIA+MES+PERIODO"),
            formula("total~DIA_NUM+I(PERIODO^2)+MES+PERIODO"),
            formula("total~DIA_NUM+MES+DIA"),
            formula("total~DIA_NUM+MES")
            ,formula("total~DIA_NUM+DIA+I(PERIODO^2)+MES+PERIODO+especial")
            ,formula("total~DIA_NUM+I(PERIODO^2)+MES+PERIODO+especial")
            ,formula("total~DIA_NUM+MES+DIA+especial")
)
com.dia.1 <- adj_model_com(formulas, TR_data, VA_data)
com.dia.1.vis <- com.dia.1[,-6]
```


##MODELO PARA COMUNA_DIAS TR=2014-2016
```{r}
TR_data <- filter(df.comuna, PERIODO!=2018 & PERIODO!=2017)
VA_data <- filter(df.comuna, PERIODO==2018 | PERIODO==2017)

formulas = c(formula("total~DIA_NUM+DIA+I(PERIODO^2)+MES+PERIODO"),
            formula("total~DIA_NUM+DIA+MES+PERIODO"),
            formula("total~DIA_NUM+I(PERIODO^2)+MES+PERIODO"),
            formula("total~DIA_NUM+MES+DIA"),
            formula("total~DIA_NUM+MES")
            ,formula("total~DIA_NUM+DIA+I(PERIODO^2)+MES+PERIODO+especial")
            ,formula("total~DIA_NUM+I(PERIODO^2)+MES+PERIODO+especial")
            ,formula("total~DIA_NUM+MES+DIA+especial")
            )
com.dia.2 <- adj_model_com(formulas, TR_data, VA_data)
com.dia.2.vis <- com.dia.2[,-6]
```

```{r}
save(com.dia.1, file = "com.dia.1.RData")
save(com.dia.2, file = "com.dia.2.RData")
save(com.dia.1, com.dia.2, file = "com.dia.1_2.RData")
```


##MODELO PARA BARRIOS_DIAS TR=2014-2017
```{r}
barrios <-test$BARRIO
TR_data <- filter(df.barrio, PERIODO!=2018, BARRIO %in% barrios)
VA_data <- filter(df.barrio, PERIODO==2018, BARRIO %in% barrios)

formulas = c(formula("total~DIA_NUM+DIA+I(PERIODO^2)+MES+PERIODO+especial"),
            formula("total~DIA_NUM+DIA+MES+especial"),
            formula("total~DIA_NUM+MES+especial"),
            formula("total~DIA_NUM+MES+PERIODO")
)
bar.dia.1 <- adj_model_com(formulas, TR_data, VA_data, T)
bar.dia.1.vis <- bar.dia.1[,-6]
```

```{r}
test <- df.barrio%>%group_by(BARRIO)%>%
  summarise(
    Total = sum(total),
    Prom = sum(total)/1498
  )

s <- filter(TR_data,BARRIO=="El Poblado")
s <- date_filler(s, "El Poblado")

s2 <- filter(TR_data,BARRIO=="Aldea Pablo VI")
s2 <- date_filler(s2, "Aldea Pablo VI")

library(pscl)
m1 <- glm(formula = formula("total~DIA_NUM+MES+especial"), data = s)
d <- predict(m1, s)
mean(sum(s2$total - d)**2)
gamlss(formula = formula("total~DIA_NUM+MES+especial"), data = s, family=NO(mu.link = "identity"))

```


##MODELO PARA BARRIOS_DIAS TR=2014-2016
```{r}
TR_data <- filter(df.barrio, PERIODO!=2018 & PERIODO!=2017)
VA_data <- filter(df.barrio, PERIODO==2018 | PERIODO==2017)

bar.dia.2 <- adj_model_com(formulas, TR_data, VA_data, T)
bar.dia.2.vis <- bar.dia.2[,-6]
```

```{r}
save(bar.dia.1, bar.dia.2, file = "Modelos_finales/bar.dia.1_2.RData")
```


```{r}
#modeltest <- gamlss(formula = formula("total~DIA_NUM+DIA+I(PERIODO^2)+MES+PERIODO+especial"), data = df.comuna[df.comuna$COMUNA=="El Poblado",], family=PO(mu.link = "identity"))

modeltest <- glm(formula = formula("total~DIA_NUM+DIA+I(PERIODO^2)+MES+PERIODO+especial"), data = df.comuna[df.comuna$COMUNA=="El Poblado",])
```




